server:
  port: 8080
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/student
  username: root
  password: root
 mvc:
  view:
   prefix: /WEB-INF/view/
   suffix: .jsp
home:
 message: Welcome to Meta-Parking Spring Project!