server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/SpringSecurityAssignment
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

